# Generated by Django 3.2.4 on 2021-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Texture')),
            ],
            options={
                'verbose_name': 'Textura',
                'verbose_name_plural': 'Texturas',
                'ordering': ['name'],
            },
        ),
    ]
