# Generated by Django 3.2.4 on 2021-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomstype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstype',
            name='name',
            field=models.CharField(help_text='Indique: Casa, Apartamento...', max_length=100, unique=True, verbose_name='Nome do Imóvel'),
        ),
    ]
