# Generated by Django 3.2.4 on 2021-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomstype', '0003_alter_roomstype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomstype',
            options={'ordering': ['name'], 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterField(
            model_name='roomstype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Ambiente'),
        ),
    ]
